name: m1
dependencies:
  - apple::tensorflow-deps
  - black
  - bokeh
  - flask
  - future
  - ipython
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - pip
  - pylint
  - python
  - requests
  - scikit-learn
  - typing-extensions
  - pip:
      - Flask-Testing
      - tensorflow-macos
      - tensorflow-metal
